export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RECEIVE_CURRENT_USER_SUCCESS = 'RECEIVE_CURRENT_USER_SUCCESS';
export const RECEIVE_CURRENT_USER_ERROR = 'RECEIVE_CURRENT_USER_ERROR';
export const CURRENT_USER_LOGOUT = 'CURRENT_USER_LOGOUT';
