export const BUYER_ORDERS_REQUEST_ORDERS = 'BUYER_ORDERS_REQUEST_ORDERS';
export const BUYER_ORDERS_RECEIVE_ORDERS_SUCCESS = 'BUYER_ORDERS_RECEIVE_ORDERS_SUCCESS';
export const BUYER_ORDERS_RECEIVE_ORDERS_ERROR = 'BUYER_ORDERS_RECEIVE_ORDERS_ERROR';

export const BUYER_ORDERS_REQUEST_CANCEL_ORDER = 'BUYER_ORDERS_REQUEST_CANCEL_ORDER';
export const BUYER_ORDERS_RECEIVE_CANCEL_ORDER_SUCCESS = 'BUYER_ORDERS_RECEIVE_CANCEL_ORDER_SUCCESS';
export const BUYER_ORDERS_RECEIVE_CANCEL_ORDER_ERROR = 'BUYER_ORDERS_RECEIVE_CANCEL_ORDER_ERROR';
 
