export const BUYER_ORDERS_REQUEST_ORDERS = 'BUYER_ORDERS_REQUEST_ORDERS';
export const BUYER_ORDERS_RECEIVE_ORDERS_SUCCESS = 'BUYER_ORDERS_RECEIVE_ORDERS_SUCCESS';
export const BUYER_ORDERS_RECEIVE_ORDERS_ERROR = 'BUYER_ORDERS_RECEIVE_ORDERS_ERROR';
