export const SELECT_PICKUP = 'SELECT_PICKUP';
export const SELECT_DELIVERY = 'SELECT_DELIVERY';
export const ADDRESS_CHANGED = 'ADDRESS_CHANGED';
export const DATE_CHANGED = 'DATE_CHANGED';
export const TIME_CHANGED = 'TIME_CHANGED';
export const QUANTITY_CHANGED = 'QUANTITY_CHANGED';
export const BUYER_EMAIL_CHANGED = 'BUYER_EMAIL_CHANGED';
export const BUYER_PHONE_CHANGED = 'BUYER_PHONE_CHANGED';

export const REQUEST_FOOD = 'REQUEST_FOOD';
export const RECEIVE_FOOD_SUCCESS = 'RECEIVE_FOOD_SUCCESS';
export const RECEIVE_FOOD_ERROR = 'RECEIVE_FOOD_ERROR';

export const REQUEST_COOK = 'REQUEST_COOK';
export const RECEIVE_COOK_SUCCESS = 'RECEIVE_COOK_SUCCESS';
export const RECEIVE_COOK_ERROR = 'RECEIVE_COOK_ERROR';

export const REQUEST_REVIEWS = 'REQUEST_REVIEWS';
export const RECEIVE_REVIEWS_SUCCESS = 'RECEIVE_REVIEWS_SUCCESS';
export const RECEIVE_REVIEWS_ERROR = 'RECEIVE_REVIEWS_ERROR';
