export const SELECT_PICKUP = 'SELECT_PICKUP';
export const SELECT_DELIVERY = 'SELECT_DELIVERY';
export const MAP_CENTER_CHANGED = 'MAP_CENTER_CHANGED';
export const ADDRESS_CHANGED = 'ADDRESS_CHANGED';

export const REQUEST_FOODS = 'REQUEST_FOODS';
export const RECEIVE_FOODS_ERROR = 'RECEIVE_FOODS_ERROR';
export const RECEIVE_FOODS_SUCCESS = 'RECEIVE_FOODS_SUCCESS';
export const CLEAR_FOODS = 'CLEAR_FOODS';
export const GEO_LOCATION_CHANGED = 'GEO_LOCATION_CHANGED';
export const REGION_CHANGED = 'REGION_CHANGED';
export const DATE_CHANGED = 'DATE_CHANGED';


