export const COOK_ORDERS_REQUEST_ORDERS = 'COOK_ORDERS_REQUEST_ORDERS';
export const COOK_ORDERS_RECEIVE_ORDERS_SUCCESS = 'COOK_ORDERS_RECEIVE_ORDERS_SUCCESS';
export const COOK_ORDERS_RECEIVE_ORDERS_ERROR = 'COOK_ORDERS_RECEIVE_ORDERS_ERROR';
