export const REQUEST_PUBLIC_USER = 'REQUEST_PUBLIC_USER';
export const RECEIVE_PUBLIC_USER_SUCCESS = 'RECEIVE_PUBLIC_USER_SUCCESS';
export const RECEIVE_PUBLIC_USER_ERROR = 'RECEIVE_PUBLIC_USER_ERROR';
